.gitignore
lib/preboots/bffs.js

cc/ @jcrugzz @indexzero @Swaagie @3rd-Eden

Pass in app.log.info to BFFS instance

---

package.json

This seems to make sense from consuming elsewhere.

[dist] expose bin

---

.travis.yml
lib/routes/assets.js
package.json
test/integration/routes/assets.test.js

Be able to handle not having a build-file source and still support asset routes

No build file source

---

README.md
lib/app.js
lib/npm/routes.js
lib/preboots/index.js
lib/preboots/npm-auth.js
package.json
test/fixtures/npm-auth/basic.js
test/fixtures/npm-auth/basic.npmrc
test/fixtures/npm-auth/invalid-basic.npmrc
test/fixtures/npm-auth/invalid-token.npmrc
test/fixtures/npm-auth/token.npmrc
test/integration/npm/auth.test.js
test/macros.js
test/mocks/index.js

review while I redo the readme if possible

Add auth using npm.auth-argument-factory

---

.gitattributes
.travis.yml
lib/middlewares/auth.js
lib/middlewares/index.js
lib/npm/preboot.js
lib/npm/publisher.js
lib/preboots/loading-bay.js
lib/preboots/npm-auth.js
lib/routes/builds.js
lib/routes/checks.js
lib/routes/packages.js
package-lock.json
package.json
test/fixtures/npm-auth/basic.js
test/integration/app.test.js
test/integration/npm/auth.test.js
test/macros.js

Travis unfortunately fails due to Cassandra integration problems but passes locally.

[fix] support auth on the whole API surface

---

lib/npm/publisher.js

This fixes it co-opting the whole router with its auth pipeline

[fix] passport does weird things when its on the router level

---

lib/middlewares/debra.js
lib/middlewares/index.js

Will see why Travis is unhappy, but this should be good to go.

Silence some of the healthcheck noise.

---

lib/npm/publisher.js
lib/npm/routes.js
lib/routes/assets.js
lib/routes/builds.js
lib/routes/healthcheck.js
lib/routes/packages.js
lib/routes/promote.js
lib/routes/release-line.js
lib/routes/swagger.js

Some basic swagger cleanup.
Adding errors codes.

Update swagger - including other status codes, better sharing of stuffs

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/regression.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
LICENSE
SECURITY.md

Default documentation

---

.github/LICENSE
CHANGELOG.md

Give credits where credits are due. 
Already added the change :)
None

[fix] give some credits to RN

---

lib/npm/routes.js

[fix] properly add docs for get

---

lib/preboots/wrhs-models.js

Support env configuration for dynamo region

[dist] support env configurable region

---

.github/workflows/ci.yml

Travis is slow and aging. This PR adds a GitHub Actions workflow to replace Travis.

[dist] Create GitHub Actions workflow

---

bin/dynamo-tables.js
lib/plugins/object.js

refactor(dynamo): replace scan with query

---

README.md
bin/dynamo-tools.js
bin/init-localstack.js
bin/s3-buckets.js
bin/s3-tools.js
lib/config.js
lib/plugins/aws.js
lib/plugins/cdn.js
lib/plugins/object.js
package-lock.json
package.json

chore(s3): setup

---

lib/config.js
lib/plugins/aws.js
lib/plugins/cdn.js
lib/routes/cdn.js
lib/warehouse.js
package-lock.json
package.json

Still draft, but ready for initial feedback gathering.

feat(cdn): add POST endpoint

---

.github/workflows/test.yaml
bin/init-localstack.js
lib/config.js
lib/routes/objects.js
lib/warehouse.js
package-lock.json
package.json
test/helper.js
test/routes/objects.test.js

Tests are coming. With this PR adding end to end tests.
Also setup github workflows to run tests automatically.

tests(objects): add

---

lib/app.js
lib/routes/cdn.js
lib/routes/objects.js
lib/routes/root.js
lib/swagger.js
npm-shrinkwrap.json
package.json
wrhs-next-spec.yml

There is still work to be done to add "openapi specs autoupdate"... But this is a good solid start.

feat(swagger): add

---

lib/plugins/object.js
lib/routes/objects.js
npm-shrinkwrap.json
package.json
test/helper.js
test/routes/objects.test.js

Minor improvements to ensure versions correctness.

fix(objects): compare and check versions correctness

---

lib/plugins/object.js
lib/routes/objects.js
test/routes/objects.test.js
wrhs-next-spec.yml

feat(rollbacks): add

---

README.md

docs(readme): add api details, cli usage and more

---

MIGRATION.md

Looking for early feedback on how to improve/change this.

docs(migration): add

---

lib/app.js
lib/middlewares/index.js

Adding support for optional security log function. This PR is for the old warehouse @6.

feat(securityLog): add support

---

lib/middlewares/index.js
lib/routes/builds.js
lib/routes/promote.js

Add more security logging to the system.

feat(security): log reqs with db/disk writes

---

README.md
lib/routes/objects.js
test/routes/objects.test.js

The purpose of this PR is to ensure that if available, the head version is returned if no version is specified with the request. If the head is not set, keep returning the latest version.

feat(object): try to return head if version not specified with request

---

MIGRATION.md
QUICKSTART.md
lib/plugins/env.js
lib/plugins/object.js
lib/routes/cdn.js
lib/routes/envs.js
lib/routes/objects.js
test/helper.js
test/routes/cdn.test.js
test/routes/envs.test.js
test/routes/objects.test.js

Additionally provides an endpoint to fetch all heads (head in each environment).

feat(object): allow publish once to all enviroments 

---

lib/plugins/object.js
lib/routes/objects.js
npm-shrinkwrap.json
test/routes/objects.test.js
wrhs-next-spec.yml

```
[
{
"version": "1.0.1",
"releaseTimestamp": 1677609500155,
"releaseDate": "2023-02-28T18:38:20.155Z"
},
{
"version": "2.0.0",
"releaseTimestamp": 1677609499994,
"releaseDate": "2023-02-28T18:38:19.994Z"
},
{
"version": "1.0.2",
"releaseTimestamp": 1677609499867,
"releaseDate": "2023-02-28T18:38:19.867Z"
},
{
"version": "1.0.1",
"releaseTimestamp": 1677609499745,
"releaseDate": "2023-02-28T18:38:19.745Z"
},
{
"version": "1.0.0",
"releaseTimestamp": 1677609499525,
"releaseDate": "2023-02-28T18:38:19.525Z"
},
{
"version": "1.0.1",
"releaseTimestamp": 1677609499373,
"releaseDate": "2023-02-28T18:38:19.373Z"
},
{
"version": "1.0.0",
"releaseTimestamp": 1677609499190,
"releaseDate": "2023-02-28T18:38:19.190Z"
}
]
```

feat(objects): add endpoint to fetch head change logs

---

bin/dynamo-tables.js
lib/plugins/env.js
lib/plugins/hook.js
lib/routes/hooks.js
npm-shrinkwrap.json
package.json
test/helper.js
test/routes/hooks.test.js

Additional PR will follow up to integrate the hook calls on the different object endpoints.

feat(hooks): add basics
